[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "chromium"]
aptPkgs = [
  "libnspr4",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libdrm2",
  "libxshmfence1",
  "libglib2.0-0",
]

[variables]
NIXPACKS_APT_PKGS = "libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libdrm2 libxshmfence1 libglib2.0-0"
CHROME_PATH = "/bin/chromium"

[start]
cmd = "npm run start"
