export interface SeedWineItem {
  idSuffix: string;
  name: string;
  subcategory?: string;
  producer?: string;
  vintage?: string;
  region?: string;
  description?: string;
  glassPrice?: number;
  bottlePrice?: number;
  order: number;
}

/** Tutti i vini al calice, raggruppati per sottocategoria nel layout */
export const WINE_AL_CALICE_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "camossi-franciacorta-saten",
    subcategory: "Metodo Classico",
    name: "Camossi Franciacorta Saten",
    description: "Chardonnay",
    glassPrice: 9,
    order: 0,
  },
  {
    idSuffix: "borgoluce-valdobbiadene",
    subcategory: "Prosecco",
    name: "Borgoluce Valdobbiadene",
    description: "Glera",
    glassPrice: 7,
    order: 1,
  },
  {
    idSuffix: "mionetto-prosecco",
    subcategory: "Prosecco",
    name: "Mionetto Prosecco",
    description: "Glera",
    glassPrice: 7,
    order: 2,
  },
  {
    idSuffix: "tramin-t-cuvee-bianco",
    subcategory: "Vini Bianchi",
    name: "Tramin T Cuvee Bianco",
    description: "Chardonnay, Pinot bianco, Sauvignon, Riesling",
    glassPrice: 8,
    order: 3,
  },
  {
    idSuffix: "olivini-elemento-lugana",
    subcategory: "Vini Bianchi",
    name: "Olivini Elemento Lugana",
    description: "Turbiana",
    glassPrice: 8,
    order: 4,
  },
  {
    idSuffix: "janare-senese",
    subcategory: "Vini Bianchi",
    name: "Janare Senese",
    description: "Falanghina",
    glassPrice: 8,
    order: 5,
  },
  {
    idSuffix: "di-lenardo-fathers-eyes",
    subcategory: "Vini Bianchi",
    name: "Di Lenardo Father's Eyes",
    description: "Chardonnay",
    glassPrice: 8,
    order: 6,
  },
  {
    idSuffix: "frescobaldi-alie",
    subcategory: "Vini Rosè",
    name: "Frescobaldi Alie'",
    description: "Syrah, Vermentino",
    glassPrice: 8,
    order: 7,
  },
  {
    idSuffix: "domini-veneti-appassimento",
    subcategory: "Vini Rossi",
    name: "Domini Veneti Appassimento",
    description: "Corvina, Corvinone, Rondinella",
    glassPrice: 9,
    order: 8,
  },
  {
    idSuffix: "frescobaldi-castiglione",
    subcategory: "Vini Rossi",
    name: "Frescobaldi Castiglione",
    description: "Sangiovese, Merlot",
    glassPrice: 9,
    order: 9,
  },
  {
    idSuffix: "argiolas-costera",
    subcategory: "Vini Rossi",
    name: "Argiolas Costera",
    description: "Cannonau",
    glassPrice: 9,
    order: 10,
  },
];

/** Vini bianchi in bottiglia, raggruppati per regione */
export const WINE_VINI_BIANCHI_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "ca-del-bosco-corte-del-lupo",
    subcategory: "Lombardia",
    producer: "Ca' del Bosco*",
    name: "Corte del Lupo Bianco",
    description: "Chardonnay, Pinot Bianco",
    bottlePrice: 45,
    order: 0,
  },
  {
    idSuffix: "ca-lojera-lugana",
    subcategory: "Lombardia",
    producer: "Ca' Lojera",
    name: "Lugana",
    description: "Lugana",
    bottlePrice: 32,
    order: 1,
  },
  {
    idSuffix: "olivini-elemento-lugana-bottle",
    subcategory: "Lombardia",
    producer: "Olivini Elemento",
    name: "Lugana",
    description: "Turbiana",
    bottlePrice: 29,
    order: 2,
  },
  {
    idSuffix: "vigneti-massa-derthona",
    subcategory: "Piemonte",
    producer: "Vigneti Massa",
    name: "Derthona",
    description: "Timorasso",
    bottlePrice: 43,
    order: 3,
  },
  {
    idSuffix: "vigneti-massa-piccolo-derthona",
    subcategory: "Piemonte",
    producer: "Vigneti Massa",
    name: "Piccolo Derthona",
    description: "Timorasso",
    bottlePrice: 30,
    order: 4,
  },
  {
    idSuffix: "vigneti-massa-derthona-sterpi",
    subcategory: "Piemonte",
    producer: "Vigneti Massa",
    name: "Derthona Sterpi",
    description: "Timorasso",
    bottlePrice: 62,
    order: 5,
  },
  {
    idSuffix: "le-battistelle-soave-classico",
    subcategory: "Veneto",
    producer: "Le Battistelle",
    name: "Soave Classico",
    description: "Garganega",
    bottlePrice: 32,
    order: 6,
  },
  {
    idSuffix: "franz-haas-sofi",
    subcategory: "Trentino",
    producer: "Franz Haas",
    name: "Sofi",
    description: "Müller Thurgau",
    bottlePrice: 28,
    order: 7,
  },
  {
    idSuffix: "hoffstater-de-vite",
    subcategory: "Trentino",
    producer: "Hoffstater",
    name: "De Vite",
    description: "Pinot Bianco, Müller Thurgau, Sauvignon, Riesling",
    bottlePrice: 30,
    order: 8,
  },
  {
    idSuffix: "hoffstatter-pinot-bianco",
    subcategory: "Trentino",
    producer: "Hoffstatter",
    name: "Pinot Bianco",
    description: "Pinot Bianco",
    bottlePrice: 28,
    order: 9,
  },
  {
    idSuffix: "hoffstatter-barthenau",
    subcategory: "Trentino",
    producer: "Hoffstatter",
    name: "Barthenau",
    description: "Pinot Bianco",
    bottlePrice: 50,
    order: 10,
  },
  {
    idSuffix: "tramin-nussbaumer",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Nussbaumer",
    description: "Gewürztraminer",
    bottlePrice: 48,
    order: 11,
  },
  {
    idSuffix: "tramin-unterebner",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Unterebner",
    description: "Pinot Grigio",
    bottlePrice: 48,
    order: 12,
  },
  {
    idSuffix: "tramin-selida",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Selida",
    description: "Gewürztraminer",
    bottlePrice: 32,
    order: 13,
  },
  {
    idSuffix: "tramin-t-cuvee-bottle",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "T Cuvee",
    description: "Chardonnay, Sauvignon, Pinot Bianco",
    bottlePrice: 29,
    order: 14,
  },
  {
    idSuffix: "tramin-chardonnay",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Chardonnay",
    description: "Chardonnay",
    bottlePrice: 28,
    order: 15,
  },
  {
    idSuffix: "tramin-sauvignon",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Sauvignon",
    description: "Sauvignon",
    bottlePrice: 28,
    order: 16,
  },
  {
    idSuffix: "tramin-pepi",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Pepi",
    description: "Sauvignon",
    bottlePrice: 35,
    order: 17,
  },
  {
    idSuffix: "kellerei-bozen-chardonnay",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Chardonnay",
    description: "Chardonnay",
    bottlePrice: 29,
    order: 18,
  },
  {
    idSuffix: "kellerei-bozen-pinot-bianco",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Pinot Bianco",
    description: "Pinot Bianco",
    bottlePrice: 28,
    order: 19,
  },
  {
    idSuffix: "kellerei-bozen-hochkofler",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Hochkofler",
    description: "Riesling",
    bottlePrice: 35,
    order: 20,
  },
  {
    idSuffix: "kellerei-bozen-sauvignon",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Sauvignon",
    description: "Sauvignon Blanc",
    bottlePrice: 28,
    order: 21,
  },
  {
    idSuffix: "vie-di-romans-chardonnay",
    subcategory: "Friuli Venezia Giulia",
    producer: "Vie di Romans",
    name: "Chardonnay",
    description: "Chardonnay",
    bottlePrice: 55,
    order: 22,
  },
  {
    idSuffix: "vie-di-romans-pier-sauvignon",
    subcategory: "Friuli Venezia Giulia",
    producer: "Vie di Romans",
    name: "Pier Sauvignon",
    description: "Sauvignon Blanc",
    bottlePrice: 55,
    order: 23,
  },
  {
    idSuffix: "borgo-del-tiglio-collio-friulano",
    subcategory: "Friuli Venezia Giulia",
    producer: "Borgo del Tiglio",
    name: "Collio Friulano",
    description: "Friulano",
    bottlePrice: 60,
    order: 24,
  },
  {
    idSuffix: "borgo-del-tiglio-collio-malvasia",
    subcategory: "Friuli Venezia Giulia",
    producer: "Borgo del Tiglio",
    name: "Collio Malvasia",
    description: "Malvasia Istriana",
    bottlePrice: 75,
    order: 25,
  },
  {
    idSuffix: "di-lenardo-fathers-eyes-bottle",
    subcategory: "Friuli Venezia Giulia",
    producer: "Di Lenardo",
    name: "Father's Eyes",
    description: "Chardonnay",
    bottlePrice: 32,
    order: 26,
  },
  {
    idSuffix: "livon-solarco",
    subcategory: "Friuli Venezia Giulia",
    producer: "Livon",
    name: "Solarco",
    description: "Friulano, Ribolla Gialla",
    bottlePrice: 35,
    order: 27,
  },
  {
    idSuffix: "livon-roncalto",
    subcategory: "Friuli Venezia Giulia",
    producer: "Livon",
    name: "Roncalto",
    description: "Ribolla Gialla",
    bottlePrice: 35,
    order: 28,
  },
  {
    idSuffix: "livon-braide-grande",
    subcategory: "Friuli Venezia Giulia",
    producer: "Livon",
    name: "Braide Grande",
    description: "Pinot Grigio",
    bottlePrice: 35,
    order: 29,
  },
  {
    idSuffix: "vie-di-romans-dole",
    subcategory: "Friuli Venezia Giulia",
    producer: "Vie di Romans",
    name: "Dole",
    description: "100% Friulano",
    bottlePrice: 50,
    order: 30,
  },
  {
    idSuffix: "janare-falanghina",
    subcategory: "Campania",
    producer: "Janare",
    name: "Falanghina",
    description: "Falanghina del Sannio",
    bottlePrice: 27,
    order: 31,
  },
  {
    idSuffix: "marisa-cuomo-fiorduva",
    subcategory: "Campania",
    producer: "Marisa Cuomo*",
    name: "Fiorduva",
    description: "Fenile, Ginestra, Ripoli",
    bottlePrice: 69,
    order: 32,
  },
  {
    idSuffix: "marisa-cuomo-furore-bianco",
    subcategory: "Campania",
    producer: "Marisa Cuomo",
    name: "Furore Bianco",
    description: "Falanghina, Biancolella",
    bottlePrice: 29,
    order: 33,
  },
  {
    idSuffix: "quintodecimo-giallo-d-arles",
    subcategory: "Campania",
    producer: "Quintodecimo",
    name: "Giallo d' Arles",
    description: "Greco di Tufo",
    bottlePrice: 52,
    order: 34,
  },
  {
    idSuffix: "quintodecimo-vie-del-campo",
    subcategory: "Campania",
    producer: "Quintodecimo",
    name: "Vie del Campo",
    description: "Fiano di Avellino",
    bottlePrice: 52,
    order: 35,
  },
  {
    idSuffix: "benito-ferrara-vigna-cicogna",
    subcategory: "Campania",
    producer: "Benito Ferrara",
    name: "Vigna Cicogna",
    description: "100% Greco di Tufo",
    bottlePrice: 38,
    order: 36,
  },
  {
    idSuffix: "tenuta-scuotto-fiano",
    subcategory: "Campania",
    producer: "Tenuta Scuotto",
    name: "Fiano",
    description: "100% Fiano",
    bottlePrice: 28,
    order: 37,
  },
  {
    idSuffix: "tenuta-scuotto-greco-di-tufo",
    subcategory: "Campania",
    producer: "Tenuta Scuotto",
    name: "Greco di Tufo",
    description: "100% Greco DOCG",
    bottlePrice: 29,
    order: 38,
  },
  {
    idSuffix: "tenuta-scuotto-falanghina",
    subcategory: "Campania",
    producer: "Tenuta Scuotto",
    name: "Falanghina",
    description: "Falanghina",
    bottlePrice: 28,
    order: 39,
  },
  {
    idSuffix: "satta-bolgheri-bianco",
    subcategory: "Toscana",
    producer: "Satta",
    name: "Bolgheri Bianco",
    description: "Vermentino, Sauvignon",
    bottlePrice: 42,
    order: 40,
  },
  {
    idSuffix: "argiolas-costamolino",
    subcategory: "Sardegna",
    producer: "Argiolas*",
    name: "Costamolino",
    description: "Vermentino di Sardegna DOC",
    bottlePrice: 32,
    order: 41,
  },
  {
    idSuffix: "case-alte-12-filari",
    subcategory: "Sicilia",
    producer: "Case Alte",
    name: "12 Filari",
    description: "Catarrato",
    bottlePrice: 32,
    order: 42,
  },
  {
    idSuffix: "case-alte-4-filari",
    subcategory: "Sicilia",
    producer: "Case Alte",
    name: "4 Filari",
    description: "Grillo",
    bottlePrice: 32,
    order: 43,
  },
  {
    idSuffix: "graci-etna-bianco",
    subcategory: "Sicilia",
    producer: "Graci",
    name: "Etna Bianco",
    description: "Carricante, Catarratto",
    bottlePrice: 36,
    order: 44,
  },
  {
    idSuffix: "dr-pauly-bergweiler-riesling",
    subcategory: "Esteri",
    producer: "Dr. Pauly",
    name: "Bergweiler Riesling Trocken",
    description: "Riesling",
    bottlePrice: 34,
    order: 45,
  },
  {
    idSuffix: "fritz-haag-brauneberger-juffer",
    subcategory: "Esteri",
    producer: "Fritz Haag",
    name: "Brauneberger Juffer Riesling",
    description: "Riesling",
    bottlePrice: 34,
    order: 46,
  },
  {
    idSuffix: "bourgeois-blanc-henri",
    subcategory: "Esteri",
    producer: "Bourgeois",
    name: "Blanc Henri",
    description: "Sauvignon Blanc",
    bottlePrice: 53,
    order: 47,
  },
  {
    idSuffix: "defaix-chablis",
    subcategory: "Esteri",
    producer: "Defaix",
    name: "Chablis",
    description: "100% Chardonnay",
    bottlePrice: 50,
    order: 48,
  },
];

/** Vini rossi in bottiglia, raggruppati per regione */
export const WINE_VINI_ROSSI_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "argiolas-turriga",
    subcategory: "Sardegna",
    producer: "Argiolas",
    name: "Turriga",
    description: "Cannonau, Carignano, Bovale, Malvasia Nera",
    bottlePrice: 120,
    order: 0,
  },
  {
    idSuffix: "argiolas-senes",
    subcategory: "Sardegna",
    producer: "Argiolas",
    name: "Senes",
    description: "Cannonau Riserva",
    bottlePrice: 45,
    order: 1,
  },
  {
    idSuffix: "argiolas-costera-bottle",
    subcategory: "Sardegna",
    producer: "Argiolas",
    name: "Costera",
    description: "Cannonau",
    bottlePrice: 32,
    order: 2,
  },
  {
    idSuffix: "graci-feudo-di-mezzo-etna-rosso",
    subcategory: "Sicilia",
    producer: "Graci",
    name: "Feudo di Mezzo Etna Rosso",
    description: "Nerello Mascalese, Nerello Cappuccio",
    bottlePrice: 67,
    order: 3,
  },
  {
    idSuffix: "graci-etna-rosso",
    subcategory: "Sicilia",
    producer: "Graci",
    name: "Etna Rosso",
    description: "Nerello Mascalese, Nerello Cappuccio",
    bottlePrice: 40,
    order: 4,
  },
  {
    idSuffix: "case-alte-16-filari",
    subcategory: "Sicilia",
    producer: "Case Alte",
    name: "16 Filari",
    description: "Nero D'Avola",
    bottlePrice: 28,
    order: 5,
  },
  {
    idSuffix: "tenuta-scuotto-taurasi",
    subcategory: "Campania",
    producer: "Tenuta Scuotto",
    name: "Taurasi",
    description: "Aglianico",
    bottlePrice: 65,
    order: 6,
  },
  {
    idSuffix: "tenuta-scuotto-aglianico",
    subcategory: "Campania",
    producer: "Tenuta Scuotto",
    name: "Aglianico",
    description: "Aglianico",
    bottlePrice: 28,
    order: 7,
  },
  {
    idSuffix: "feudi-di-san-gregorio-taurasi",
    subcategory: "Campania",
    producer: "Feudi di San Gregorio",
    name: "Taurasi",
    description: "Aglianico",
    bottlePrice: 55,
    order: 8,
  },
  {
    idSuffix: "marisa-cuomo-furore-rosso",
    subcategory: "Campania",
    producer: "Marisa Cuomo",
    name: "Furore Rosso",
    description: "Piedirosso, Aglianico",
    bottlePrice: 38,
    order: 9,
  },
  {
    idSuffix: "marisa-cuomo-furore-rosso-riserva",
    subcategory: "Campania",
    producer: "Marisa Cuomo",
    name: "Furore Rosso Riserva",
    description: "Piedirosso, Aglianico",
    bottlePrice: 55,
    order: 10,
  },
  {
    idSuffix: "montevetrano-montevetrano",
    subcategory: "Campania",
    producer: "Montevetrano",
    name: "Montevetrano",
    description: "Cabernet Sauvignon, Merlot, Aglianico",
    bottlePrice: 80,
    order: 11,
  },
  {
    idSuffix: "janare-aglianico-lucchero",
    subcategory: "Campania",
    producer: "Janare",
    name: "Aglianico Lucchero",
    description: "Aglianico",
    bottlePrice: 30,
    order: 12,
  },
  {
    idSuffix: "janare-cantari-riserva",
    subcategory: "Campania",
    producer: "Janare",
    name: "Cantari Riserva",
    description: "Aglianico",
    bottlePrice: 38,
    order: 13,
  },
  {
    idSuffix: "grattamacco-bolgheri-superiore",
    subcategory: "Toscana",
    producer: "Grattamacco",
    name: "Bolgheri Superiore",
    description: "Cabernet Sauvignon, Merlot, Sangiovese",
    bottlePrice: 115,
    order: 14,
  },
  {
    idSuffix: "costanti-brunello-di-montalcino",
    subcategory: "Toscana",
    producer: "Costanti",
    name: "Brunello di Montalcino",
    description: "100% Sangiovese",
    bottlePrice: 99,
    order: 15,
  },
  {
    idSuffix: "costanti-rosso-di-montalcino",
    subcategory: "Toscana",
    producer: "Costanti",
    name: "Rosso di Montalcino",
    description: "Sangiovese",
    bottlePrice: 40,
    order: 16,
  },
  {
    idSuffix: "frescobaldi-castelgiocondo",
    subcategory: "Toscana",
    producer: "Frescobaldi",
    name: "Castelgiocondo",
    description: "Sangiovese",
    bottlePrice: 55,
    order: 17,
  },
  {
    idSuffix: "gaja-ca-marcanda-magari",
    subcategory: "Toscana",
    producer: "Gaja",
    name: "Ca' Marcanda Magari",
    description: "Merlot, Cabernet Sauvignon, Cabernet Franc",
    bottlePrice: 85,
    order: 18,
  },
  {
    idSuffix: "roccapesta-morellino-di-scansano",
    subcategory: "Toscana",
    producer: "Roccapsta",
    name: "Morellino di Scansano",
    description: "Sangiovese, Ciliegiolo",
    bottlePrice: 32,
    order: 19,
  },
  {
    idSuffix: "michele-satta-bolgheri-rosso",
    subcategory: "Toscana",
    producer: "Michele Satta",
    name: "Bolgheri Rosso",
    description: "Syrah, Sangiovese, Cabernet Sauvignon, Merlot",
    bottlePrice: 45,
    order: 20,
  },
  {
    idSuffix: "tenuta-dell-ornellaia-le-volte",
    subcategory: "Toscana",
    producer: "Tenuta dell'Ornellaia",
    name: "Le Volte",
    description: "Merlot, Sangiovese, Cabernet Sauvignon",
    bottlePrice: 39,
    order: 21,
  },
  {
    idSuffix: "frescobaldi-castiglione-bottle",
    subcategory: "Toscana",
    producer: "Frescobaldi",
    name: "Castiglione",
    description: "Chianti",
    bottlePrice: 32,
    order: 22,
  },
  {
    idSuffix: "ca-del-bosco-corte-del-lupo-rosso",
    subcategory: "Lombardia",
    producer: "Ca' del Bosco",
    name: "Corte del Lupo Rosso",
    description: "Merlot, Cabernet Sauvignon, Cabernet Franc, Carmenere",
    bottlePrice: 45,
    order: 23,
  },
  {
    idSuffix: "gaja-barbaresco",
    subcategory: "Piemonte",
    producer: "Gaja",
    name: "Barbaresco",
    description: "100% Nebbiolo",
    bottlePrice: 280,
    order: 24,
  },
  {
    idSuffix: "bruno-rocca-curra",
    subcategory: "Piemonte",
    producer: "Bruno Rocca",
    name: "Curra'",
    description: "100% Nebbiolo",
    bottlePrice: 128,
    order: 25,
  },
  {
    idSuffix: "bruno-rocca-fralu",
    subcategory: "Piemonte",
    producer: "Bruno Rocca",
    name: "Fralu'",
    description: "Barbera, Nebbiolo",
    bottlePrice: 40,
    order: 26,
  },
  {
    idSuffix: "bruno-rocca-barbaresco",
    subcategory: "Piemonte",
    producer: "Bruno Rocca",
    name: "Barbaresco",
    description: "100% Nebbiolo",
    bottlePrice: 65,
    order: 27,
  },
  {
    idSuffix: "tre-di-berri-nebbiolo",
    subcategory: "Piemonte",
    producer: "Tre di Berri",
    name: "Nebbiolo",
    description: "Nebbiolo",
    bottlePrice: 34,
    order: 28,
  },
  {
    idSuffix: "tre-di-berri-barbera",
    subcategory: "Piemonte",
    producer: "Tre di Berri",
    name: "Barbera",
    description: "Barbera",
    bottlePrice: 32,
    order: 29,
  },
  {
    idSuffix: "tre-di-berri-barolo",
    subcategory: "Piemonte",
    producer: "Tre di Berri",
    name: "Barolo",
    description: "Nebbiolo",
    bottlePrice: 85,
    order: 30,
  },
  {
    idSuffix: "tre-di-berri-dogliani",
    subcategory: "Piemonte",
    producer: "Tre di Berri",
    name: "Dogliani",
    description: "100% Dolcetto",
    bottlePrice: 32,
    order: 31,
  },
  {
    idSuffix: "fontanafredda-barolo",
    subcategory: "Piemonte",
    producer: "Fontanafredda",
    name: "Barolo",
    description: "Nebbiolo",
    bottlePrice: 70,
    order: 32,
  },
  {
    idSuffix: "giovanni-almondo-langhe-nebbiolo",
    subcategory: "Piemonte",
    producer: "Giovanni Almondo",
    name: "Langhe Nebbiolo",
    description: "Nebbiolo",
    bottlePrice: 35,
    order: 33,
  },
  {
    idSuffix: "tommaso-bussola-amarone",
    subcategory: "Veneto",
    producer: "Tommaso Bussola",
    name: "Amarone della Valpolicella",
    description: "Corvinone, Corvina, Rondinella, Molinara",
    bottlePrice: 86,
    order: 34,
  },
  {
    idSuffix: "tommaso-bussola-ca-del-laito",
    subcategory: "Veneto",
    producer: "Tommaso Bussola",
    name: "Ca' del Laito Valpolicella Ripasso",
    description: "Corvinone, Corvina, Rondinella, Molinara",
    bottlePrice: 50,
    order: 35,
  },
  {
    idSuffix: "brigaldara-ilvegro",
    subcategory: "Veneto",
    producer: "Brigaldara",
    name: "Ilvegro Valpolicella Ripasso Superiore",
    description: "Corvina, Corvinone, Rondinella",
    bottlePrice: 33,
    order: 36,
  },
  {
    idSuffix: "domini-veneti-valpolicella-ripasso",
    subcategory: "Veneto",
    producer: "Domini Veneti",
    name: "Valpolicella Classico Ripasso",
    description: "Corvina, Corvinone, Rondinella",
    bottlePrice: 35,
    order: 37,
  },
  {
    idSuffix: "domini-veneti-appassimento-bottle",
    subcategory: "Veneto",
    producer: "Domini Veneti",
    name: "Appassimento",
    description: "Corvina, Corvinone, Rondinella",
    bottlePrice: 30,
    order: 38,
  },
  {
    idSuffix: "masi-costasera-riserva",
    subcategory: "Veneto",
    producer: "Masi",
    name: "Costasera Riserva",
    description: "Corvina, Rondinella, Molinara",
    bottlePrice: 82,
    order: 39,
  },
  {
    idSuffix: "masi-brolo-campofiorin",
    subcategory: "Veneto",
    producer: "Masi",
    name: "Brolo Campofiorin",
    description: "Corvina, Rondinella, Oseleta",
    bottlePrice: 36,
    order: 40,
  },
  {
    idSuffix: "stroblhof-blauburgunder",
    subcategory: "Trentino",
    producer: "Stroblhof",
    name: "Blauburgunder",
    description: "Pinot Nero",
    bottlePrice: 73,
    order: 41,
  },
  {
    idSuffix: "tramin-marjun",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Marjun",
    description: "Pinot Nero",
    bottlePrice: 32,
    order: 42,
  },
  {
    idSuffix: "tramin-lagrein",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Lagrein",
    description: "Lagrein",
    bottlePrice: 29,
    order: 43,
  },
  {
    idSuffix: "tramin-urban-riserva",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Urban Riserva",
    description: "Lagrein",
    bottlePrice: 52,
    order: 44,
  },
  {
    idSuffix: "tramin-blauburgunder",
    subcategory: "Trentino",
    producer: "Tramin",
    name: "Blauburgunder",
    description: "Pinot Nero",
    bottlePrice: 50,
    order: 45,
  },
  {
    idSuffix: "hofstatter-meczan",
    subcategory: "Trentino",
    producer: "Hofstatter",
    name: "Meczan",
    description: "Pinot Nero",
    bottlePrice: 30,
    order: 46,
  },
  {
    idSuffix: "hofstatter-schiava",
    subcategory: "Trentino",
    producer: "Hofstatter",
    name: "Schiava",
    description: "Schiava",
    bottlePrice: 28,
    order: 47,
  },
  {
    idSuffix: "franz-haas-pinot-nero",
    subcategory: "Trentino",
    producer: "Franz Haas",
    name: "Pinot Nero",
    description: "Pinot Nero",
    bottlePrice: 38,
    order: 48,
  },
  {
    idSuffix: "kellerei-bozen-huck-am-bach",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Huck am Bach",
    description: "Schiava, Lagrein",
    bottlePrice: 28,
    order: 49,
  },
  {
    idSuffix: "kellerei-bozen-perl",
    subcategory: "Trentino",
    producer: "Kellerei Bozen",
    name: "Perl",
    description: "Lagrein",
    bottlePrice: 35,
    order: 50,
  },
  {
    idSuffix: "borgo-del-tiglio-collio-rosso-riserva",
    subcategory: "Friuli Venezia Giulia",
    producer: "Borgo del Tiglio",
    name: "Collio Rosso Riserva",
    description: "Rosso Riserva",
    bottlePrice: 90,
    order: 51,
  },
  {
    idSuffix: "zorzettig-myo",
    subcategory: "Friuli Venezia Giulia",
    producer: "Zorzettig",
    name: "Myo",
    description: "Schioppettino",
    bottlePrice: 52,
    order: 52,
  },
  {
    idSuffix: "torre-rosazza-grave",
    subcategory: "Friuli Venezia Giulia",
    producer: "Torre Rosazza",
    name: "Grave",
    description: "Pinot Nero",
    bottlePrice: 32,
    order: 53,
  },
  {
    idSuffix: "le-vigne-di-zamo-merlot",
    subcategory: "Friuli Venezia Giulia",
    producer: "Le Vigne di Zamo'",
    name: "Merlot",
    description: "Merlot",
    bottlePrice: 28,
    order: 54,
  },
];

/** Vini rosati in bottiglia */
export const WINE_VINI_ROSATI_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "frescobaldi-alie-bottle",
    producer: "Frescobaldi",
    name: "Alie'",
    description: "Syrah, Vermentino",
    bottlePrice: 28,
    order: 0,
  },
  {
    idSuffix: "franz-haas-vigneti-dolomiti-rose",
    producer: "Franz Haas",
    name: "Vigneti delle Dolomiti Rose'",
    description: "Pinot Nero",
    bottlePrice: 38,
    order: 1,
  },
];

/** Metodo classico in bottiglia */
export const WINE_METODO_CLASSICO_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "ca-del-bosco-cuvee-prestige",
    producer: "Ca' del Bosco*",
    name: "Cuvee Prestige",
    description: "Chardonnay, Pinot Nero, Pinot Bianco",
    bottlePrice: 58,
    order: 0,
  },
  {
    idSuffix: "ca-del-bosco-vintage-collection",
    producer: "Ca' del Bosco",
    name: "Vintage Collection",
    description: "Chardonnay, Pinot Nero, Pinot Bianco",
    bottlePrice: 79,
    order: 1,
  },
  {
    idSuffix: "camillucci-ammonites-dosaggio-zero",
    producer: "Camillucci",
    name: "Ammonites Dosaggio Zero",
    description: "Chardonnay, Pinot Nero",
    bottlePrice: 36,
    order: 2,
  },
  {
    idSuffix: "camillucci-ammonites-saten",
    producer: "Camillucci",
    name: "Ammonites Saten",
    description: "Chardonnay, Pinot Bianco",
    bottlePrice: 42,
    order: 3,
  },
  {
    idSuffix: "camillucci-antology-noir",
    producer: "Camillucci",
    name: "Antology Noir",
    description: "Pinot Nero",
    bottlePrice: 50,
    order: 4,
  },
  {
    idSuffix: "camossi-pietro-camossi",
    producer: "Camossi",
    name: "Pietro Camossi",
    description: "Pinot Noir",
    bottlePrice: 60,
    order: 5,
  },
  {
    idSuffix: "camossi-franciacorta-dosaggio-zero",
    producer: "Camossi",
    name: "Franciacorta Dosaggio Zero",
    description: "Chardonnay, Pinot Nero",
    bottlePrice: 45,
    order: 6,
  },
  {
    idSuffix: "camossi-extra-brut",
    producer: "Camossi",
    name: "Extra Brut",
    description: "Chardonnay, Pinot Nero",
    bottlePrice: 36,
    order: 7,
  },
  {
    idSuffix: "camossi-franciacorta-rose",
    producer: "Camossi",
    name: "Franciacorta Rosé",
    description: "Pinot Nero, Chardonnay",
    bottlePrice: 41,
    order: 8,
  },
  {
    idSuffix: "camossi-franciacorta-saten-bottle",
    producer: "Camossi",
    name: "Franciacorta Saten",
    description: "Chardonnay",
    bottlePrice: 42,
    order: 9,
  },
  {
    idSuffix: "ferrari-trento-brut-perle-rose",
    producer: "Ferrari",
    name: "Trento Brut Perlè Rose'",
    description: "Chardonnay, Pinot nero",
    bottlePrice: 120,
    order: 10,
  },
  {
    idSuffix: "ferrari-trento-doc-perle",
    producer: "Ferrari",
    name: "Trento DOC Perlè",
    description: "Chardonnay",
    bottlePrice: 85,
    order: 11,
  },
  {
    idSuffix: "ferrari-giulio",
    producer: "Ferrari",
    name: "Giulio",
    description: "Chardonnay",
    bottlePrice: 250,
    order: 12,
  },
  {
    idSuffix: "murgo-metodo-classico",
    producer: "Murgò",
    name: "Metodo Classico",
    description: "Chardonnay",
    bottlePrice: 38,
    order: 13,
  },
  {
    idSuffix: "quartomoro-metodo-classico",
    producer: "Quartomoro",
    name: "Metodo Classico",
    description: "Vermentino",
    bottlePrice: 36,
    order: 14,
  },
  {
    idSuffix: "hoffstatter-michei-trento-doc",
    producer: "Hoffstatter*",
    name: "\"Michei\" Trento DOC",
    description: "100% Chardonnay",
    bottlePrice: 40,
    order: 15,
  },
  {
    idSuffix: "monfort-cuvee-85-trento-doc",
    producer: "Monfort",
    name: "Cuvee 85 Trento DOC",
    description: "Chardonnay Pinot Nero",
    bottlePrice: 36,
    order: 16,
  },
  {
    idSuffix: "monfort-brut-rose-trento-doc",
    producer: "Monfort",
    name: "Brut Rosé Trento DOC",
    description: "Chardonnay Pinot Nero",
    bottlePrice: 38,
    order: 17,
  },
];

/** Prosecco in bottiglia */
export const WINE_PROSECCO_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "borgoluce-prosecco",
    producer: "Borgoluce",
    name: "Prosecco",
    description: "Glera",
    bottlePrice: 28,
    order: 0,
  },
  {
    idSuffix: "mionetto-prosecco-bottle",
    producer: "Mionetto",
    name: "Prosecco",
    description: "Glera",
    bottlePrice: 26,
    order: 1,
  },
];

/** Champagne in bottiglia */
export const WINE_CHAMPAGNE_ITEMS: readonly SeedWineItem[] = [
  {
    idSuffix: "roederer-cristal",
    producer: "Roederer",
    name: "Cristal",
    vintage: "2013",
    description: "Pinot Nero, Chardonnay",
    bottlePrice: 320,
    order: 0,
  },
  {
    idSuffix: "ruinart-blanc-de-blancs",
    producer: "Ruinart",
    name: "Blanc de Blancs",
    description: "Chardonnay",
    bottlePrice: 245,
    order: 1,
  },
  {
    idSuffix: "ruinart-brut-rose",
    producer: "Ruinart",
    name: "Brut Rosè",
    vintage: "2013",
    description: "Pinot Nero, Chardonnay",
    bottlePrice: 245,
    order: 2,
  },
  {
    idSuffix: "gosset-extra-brut",
    producer: "Gosset",
    name: "Extra Brut",
    vintage: "2013",
    description: "Pinot Noir, Pinot Meunier, Chardonnay",
    bottlePrice: 100,
    order: 3,
  },
  {
    idSuffix: "gosset-blanc-de-blancs",
    producer: "Gosset",
    name: "Blanc de Blancs",
    vintage: "2013",
    description: "Chardonnay",
    bottlePrice: 133,
    order: 4,
  },
  {
    idSuffix: "gosset-brut-rose",
    producer: "Gosset",
    name: "Brut Rosé",
    description: "Chardonnay, Pinot Noir, Vin Rouge",
    bottlePrice: 128,
    order: 5,
  },
  {
    idSuffix: "gosset-brut-grand-millesime",
    producer: "Gosset",
    name: "Brut Grand Millesime",
    vintage: "2012",
    description: "Chardonnay, Pinot Noir",
    bottlePrice: 155,
    order: 6,
  },
  {
    idSuffix: "guy-de-forez-brut-rose",
    producer: "Guy de Forez",
    name: "Brut Rose'",
    description: "Pinot Noir",
    bottlePrice: 58,
    order: 7,
  },
  {
    idSuffix: "guy-de-forez-brut-tradition",
    producer: "Guy de Forez",
    name: "Brut Tradition",
    description: "Pinot Noir",
    bottlePrice: 56,
    order: 8,
  },
  {
    idSuffix: "moet-chandon-brut-imperial",
    producer: "Moët & Chandon",
    name: "Brut Imperial",
    description: "Pinot Noir, Pinot Meunier, Chardonnay",
    bottlePrice: 120,
    order: 9,
  },
  {
    idSuffix: "dom-perignon-vintage-brut",
    producer: "Dom Perignon",
    name: "Vintage Brut",
    description: "Pinot Noir, Chardonnay",
    bottlePrice: 700,
    order: 10,
  },
  {
    idSuffix: "fresnet-juillet-grand-cru-rose",
    producer: "Fresnet Juillet",
    name: "Grand Cru Rosè",
    description: "Pinot Nero, Chardonnay",
    bottlePrice: 77,
    order: 11,
  },
  {
    idSuffix: "fresnet-juillet-brut-cuvee-vincent",
    producer: "Fresnet Juillet",
    name: "Brut Cuvée Vincent Pinot Noir",
    description: "Pinot Nero",
    bottlePrice: 113,
    order: 12,
  },
];

export const WINE_CATEGORIES = [
  {
    idSuffix: "al-calice",
    name: "Al calice",
    order: 0,
    items: WINE_AL_CALICE_ITEMS,
  },
  {
    idSuffix: "vini-bianchi",
    name: "Vini Bianchi",
    order: 1,
    items: WINE_VINI_BIANCHI_ITEMS,
  },
  {
    idSuffix: "vini-rossi",
    name: "Vini Rossi",
    order: 2,
    items: WINE_VINI_ROSSI_ITEMS,
  },
  {
    idSuffix: "vini-rosati",
    name: "Vini Rosati",
    order: 3,
    items: WINE_VINI_ROSATI_ITEMS,
  },
  {
    idSuffix: "metodo-classico",
    name: "Metodo Classico",
    order: 4,
    items: WINE_METODO_CLASSICO_ITEMS,
  },
  {
    idSuffix: "prosecco",
    name: "Prosecco",
    order: 5,
    items: WINE_PROSECCO_ITEMS,
  },
  {
    idSuffix: "champagne",
    name: "Champagne",
    order: 6,
    items: WINE_CHAMPAGNE_ITEMS,
  },
] as const;
